/* ============================================================
   Reference curriculum data — transcribed from the College of
   Maasin's official program curricula. Used to look up the real
   subjects a student should be taking, keyed by program (+ major,
   where the program has one) and year level.

   Only programs/majors for which an official curriculum sheet was
   provided are included here; getCurriculumSubjects() returns an
   empty array for anything else.
   ============================================================ */

interface CurriculumSubject {
  code: string;
  name: string;
}

type CurriculumByYear = Record<string, CurriculumSubject[]>;
type CurriculumTable = Record<string, CurriculumByYear>;

/* Keys match the exact <option value> strings used by the
   Program / Major selects in pages/applicants.php. A program with
   a major uses the composite key "<program>|<major>". */
const CURRICULUM_DATA: CurriculumTable = {
  "BS Nursing": {
    "1st Year": [
      { code: "GEC 01", name: "Understanding the Self" },
      { code: "GEC 02", name: "Readings in the Phil. History" },
      { code: "REL 01", name: "Old Testament" },
      { code: "NCM 100", name: "Theoretical Foundation in Nursing" },
      { code: "BIO 101", name: "Anatomy & Physiology" },
      { code: "CHEM 101", name: "Biochemistry" },
      { code: "GEC 03", name: "Mathematics in the Modern World" },
      { code: "PE 101", name: "Physical Education (Wellness & Fitness)" },
      { code: "GE 04", name: "Komunikasyon sa Akademikong Filipino" },
      { code: "GEC 06", name: "Purposive Communication (w/ Technical Writing)" },
      { code: "NCM 101", name: "Health Assessment" },
      { code: "NPS 01", name: "Health Education" },
      { code: "NCM 102", name: "Fundamentals of Nursing Practice" },
      { code: "BIO 102", name: "Microbiology & Parasitology" },
      { code: "GE 05", name: "Philippine Literature" },
      { code: "PE 102", name: "Physical Education (Self-Defense)" },
      { code: "REL 02", name: "New Testament" },
    ],
    "2nd Year": [
      { code: "NCM 103", name: "Community Health Nursing 1 (Individual and Family as Clients)" },
      { code: "NPS 02", name: "Nutrition and Diet Therapy" },
      { code: "NPS 03", name: "Pharmacology" },
      { code: "NCM 104", name: "Care of Mother, Child, Adolescent (Well Clients)" },
      { code: "NSTP 1", name: "National Service Training Program" },
      { code: "PE 3", name: "Physical Education 3 (Swimming)" },
      { code: "GEC 08", name: "Sining ng Pakikipagtalastasan" },
      { code: "REL 03", name: "Biblical Interpretation" },
      { code: "NCM 105", name: "Care of Mother, Child at Risks or with Problems (Acute and Chronic)" },
      { code: "GEC 07", name: "Ethics" },
      { code: "NSTP 2", name: "National Service Training Program" },
      { code: "PE 4", name: "Physical Education 4 (Sports)" },
      { code: "GEC 09", name: "Art Appreciation" },
      { code: "NPS 04", name: "Nursing Informatics" },
      { code: "GEC 10", name: "Science, Technology and Society" },
      { code: "NPS 05", name: "Health Care Ethics (Bioethics)" },
    ],
    "3rd Year": [
      { code: "NPS 06", name: "Nursing Research 1" },
      { code: "NCM 106", name: "Care of Clients with Problems in Oxygenation, Fluid and Electrolytes, Infections, Inflammatory and Immunologic Response, Cellular Abberations, Acute and Chronic" },
      { code: "NCM 107", name: "Community Health Nursing 2 (Population Groups and Community as Clients)" },
      { code: "NCM 108", name: "Care of Older Adult" },
      { code: "NPS 07", name: "Nursing Research 2" },
      { code: "NCM 109", name: "Care of Clients with Problems in Nutrition, and Gastro-Intestinal, Metabolism and Endocrine, Perception and Coordination (Acute and Chronic)" },
      { code: "NCM 110", name: "Care of Clients with Maladaptive Patterns of Behavior, Acute and Chronic" },
      { code: "PHILO 302", name: "Logic and Critical Thinking" },
    ],
    "4th Year": [
      { code: "NCM 111", name: "Nursing Care of Clients with Life Threatening Conditions Acutely Ill/Multi-Organ Problem, High Acuity and Emergency Situation, Acute and Chronic" },
      { code: "NCM 112", name: "Nursing Leadership and Management" },
      { code: "NPS 08", name: "Decent Work Employment and Transcultural Nursing" },
      { code: "GEC 11", name: "The Contemporary World" },
      { code: "RIZAL 1", name: "Life, Works and Writings of Rizal" },
      { code: "NCM 113", name: "Disaster Nursing" },
      { code: "NCM 114", name: "Intensive Nursing Practicum (Hospital and Community Settings)" },
      { code: "EC 01", name: "Integrated Enhancement Course" },
    ],
  },

  "BS Business Administration|Human Resource Development Management (HRDM)": {
    "1st Year": [
      { code: "GE1", name: "Understanding the Self" },
      { code: "GE2", name: "Reading in Philippine History" },
      { code: "GE3", name: "The Contemporary World" },
      { code: "GE4", name: "Mathematics in Modern World" },
      { code: "Acctg 21", name: "Fundamental of Accounting (Bridge for non-ABM students) Part 1" },
      { code: "PATHFIT 1", name: "Physical Activities Toward Health & Fitness 1 (Movement Competency Training)" },
      { code: "REL 1", name: "The Old Testament" },
      { code: "NSTP 1", name: "National Service Training Program" },
      { code: "GE 5", name: "Purposive Communication" },
      { code: "GE 6", name: "Art Appreciation" },
      { code: "GE 7", name: "Science, Technology & Society" },
      { code: "GE 8", name: "Ethics" },
      { code: "REL 2", name: "The New Testament" },
      { code: "GE Elec 1", name: "Living in IT Era" },
      { code: "Math 25", name: "Math of Investment" },
      { code: "PATHFIT 2", name: "Physical Activities Toward Health & Fitness 2 (Exercise-Based Fitness Activities)" },
      { code: "NSTP 2", name: "National Service Training Program" },
    ],
    "2nd Year": [
      { code: "GE Elec 2", name: "Gender and Society" },
      { code: "BA Core1", name: "Basic Microeconomics" },
      { code: "BA Core2", name: "Obligation and Contracts" },
      { code: "BA Core3", name: "Income Taxation" },
      { code: "BA Inst 1", name: "Human Behavior of Organization" },
      { code: "PATHFIT 3", name: "Physical Activities Toward Health & Fitness 3 (Sports)" },
      { code: "Rel 21", name: "Biblical Interpretation in Phil Context" },
      { code: "GE 9", name: "Rizal's Life & Works" },
      { code: "GE Elec 1", name: "Philippine Popular Culture" },
      { code: "BA Core4", name: "Good Governance & Social Responsibility" },
      { code: "Prof1-HRDM41", name: "Administrative & Office Management" },
      { code: "Prof2-HRDM45", name: "Labor Law and Legislation" },
      { code: "Elec1-HRE", name: "Logistics Management" },
      { code: "PATHFIT 4", name: "Physical Activities Toward Health & Fitness 4 (Dance)" },
    ],
    "3rd Year": [
      { code: "CBMEC1", name: "Total Quality Management" },
      { code: "BA Core5", name: "Human Resource Management" },
      { code: "BA Core6", name: "International Trade and Agreements" },
      { code: "Prof3-HRDM47", name: "Labor Relations & Negotiations" },
      { code: "Prof4-HRDM51", name: "Compensation Administration" },
      { code: "Elec2-Mgt49", name: "Entrepreneurial Management" },
      { code: "BA Core7", name: "Business Research" },
      { code: "Elec3-Mgt46", name: "Production and Operation Management" },
      { code: "Prof5-HRDM42", name: "Recruitment & Selection" },
      { code: "Prof6-HRDM44", name: "Training Development" },
      { code: "Prof7-HRDM60", name: "Organizational Development" },
      { code: "BA Inst 2", name: "Transfer and Business Tax" },
    ],
    "4th Year": [
      { code: "BA Core8", name: "Thesis/Feasibility Study" },
      { code: "Prof8-HRDM62", name: "Special Topics in HR Management" },
      { code: "Elec4-Mgt47", name: "Managerial Accounting" },
      { code: "Elec5-Mgt62", name: "Marketing Management" },
      { code: "CBMEC2", name: "Strategic Management" },
      { code: "OJT", name: "Practicum, Seminar and Field Trip" },
    ],
  },

  "BS Accountancy": {
    "1st Year": [
      { code: "GE 1", name: "Understanding the Self/ Pag-unawa sa Sarili" },
      { code: "GE 2", name: "Readings in Philippine History" },
      { code: "GE 3", name: "The Contemporary World/ Ang Kasalukuyang Daigdig" },
      { code: "AE 1", name: "Fundamentals of Accounting (Bridging)" },
      { code: "AE 2", name: "Economic Development" },
      { code: "CBME 1", name: "Operations Management & TQM" },
      { code: "NSTP 1", name: "National Service Training Program I" },
      { code: "PE 1", name: "PATHFit 1: Movement Competency Training" },
      { code: "REL 1", name: "Old Testament" },
      { code: "GE 4", name: "Mathematics in the Modern World" },
      { code: "GE 5", name: "Purposive Communication/ Malayuning Komunikasyon" },
      { code: "AE 3", name: "Managerial Economics" },
      { code: "AE 4", name: "Financial Accounting and Reporting" },
      { code: "AE 5", name: "Management Science" },
      { code: "AE 6", name: "Conceptual Framework and Accounting Standards" },
      { code: "NSTP 2", name: "National Service Training Program II" },
      { code: "PE 2", name: "PATHFit 2: Exercise-Based Fitness Activities" },
      { code: "REL 2", name: "The New Testament" },
    ],
    "2nd Year": [
      { code: "GE 6", name: "Art Appreciation/ Pagpapahalaga sa Sining" },
      { code: "AE 7", name: "Intermediate Accounting, I" },
      { code: "AE 8", name: "Cost Accounting and Control" },
      { code: "AE 9", name: "Laws on Obligations and Contracts" },
      { code: "AE 10", name: "Income Taxation" },
      { code: "AE 11", name: "Financial Management" },
      { code: "AE 12", name: "IT Application and Tools in Business" },
      { code: "PE 3", name: "PATHFit 3: Sports" },
      { code: "REL 3", name: "Biblical Interpretation" },
      { code: "GE 7", name: "Science, Technology, and Society" },
      { code: "AE 13", name: "Intermediate Accounting II" },
      { code: "AE 14", name: "Strategic Cost Management" },
      { code: "AE 15", name: "Business Laws and Regulations" },
      { code: "AE 16", name: "Business Taxation" },
      { code: "AE 17", name: "Governance, Business Ethics, Risk Management, and Internal Control" },
      { code: "AE 18", name: "Financial Market" },
      { code: "AE 19", name: "Accounting Information System" },
      { code: "PE 4", name: "PATHFit 4: Dance" },
    ],
    "3rd Year": [
      { code: "GE 8", name: "Math, Science & Technology (Living in the IT Era)" },
      { code: "AE 20", name: "Regulatory Framework and Legal Issues in Business" },
      { code: "AE 21", name: "Intermediate Accounting, III" },
      { code: "PRE-E 1", name: "Auditing and Assurance Principles" },
      { code: "PRE-E 2", name: "Accounting for Special Transactions" },
      { code: "PRE-E 3", name: "Accounting for Business Combinations" },
      { code: "PRE-E 4", name: "Auditing and Assurance Concepts and Applications I" },
      { code: "ELEC 1", name: "Human Behavior in an Organization" },
      { code: "GE 9", name: "Principles of Ethics" },
      { code: "AE 22", name: "Statistical Analysis with Software Application" },
      { code: "AE 23", name: "International Business and Trade" },
      { code: "PRE-E 5", name: "Accounting for Government and Non-Profit Organizations" },
      { code: "PRE-E 6", name: "Auditing and Assurance Concepts and Applications II" },
      { code: "PRE-E 7", name: "Auditing and Assurance for Specialized Industries" },
      { code: "PRE-E 8", name: "Auditing in a CIS Environment" },
      { code: "ELEC 2", name: "Operations Auditing" },
      { code: "AE 24", name: "Accounting Research and Methods" },
    ],
    "4th Year": [
      { code: "AE 25", name: "Accounting Internship" },
      { code: "AE 26", name: "Accountancy Research" },
      { code: "AE 1a", name: "Enhancement Course" },
      { code: "CBME 2", name: "Strategic Management" },
      { code: "AE 27", name: "Strategic Business Analysis" },
      { code: "ELEC 3", name: "Updates in Financial Reporting and Standards" },
      { code: "ELEC 4", name: "Principles and Methods in Teaching Accounting" },
      { code: "GE 10", name: "Rizal's Life and Works" },
      { code: "GE 11", name: "Arts & Humanities (Philippine Popular Culture in Pilipino Language)" },
      { code: "GE 12", name: "Social Science & Philosophy (The Entrepreneurial Mind)" },
      { code: "AE 1b", name: "Enhancement Course" },
    ],
  },

  "Bachelor of Secondary Education|English": {
    "1st Year": [
      { code: "GE1", name: "Understanding the Self" },
      { code: "GE2", name: "Readings in Philippine History" },
      { code: "GE3", name: "The Contemporary World" },
      { code: "GE4", name: "Mathematics in the Modern World" },
      { code: "EL1", name: "Introduction to Linguistics" },
      { code: "PROFED1", name: "The Child & Adolescent Learners & Learning Principles" },
      { code: "PATHFIT1", name: "Physical Activities Toward Health and Fitness 1: Movement Competency Training" },
      { code: "NSTP1", name: "National Service Training Program 1" },
      { code: "REL 1", name: "The Old Testament" },
      { code: "HUMSS1", name: "Philippine Politics & Governance" },
      { code: "ENG 1", name: "Basic English 1" },
      { code: "GE5", name: "Purposive Communication" },
      { code: "GE6", name: "Art Appreciation" },
      { code: "GE7", name: "Science, Technology & Society" },
      { code: "GE8", name: "Ethics" },
      { code: "EL3", name: "Structures of English" },
      { code: "EL2", name: "Language, Culture & Society" },
      { code: "PROFED2", name: "Technology for Teaching & Learning 1" },
      { code: "PATHFIT2", name: "Physical Activities Toward Health and Fitness 2: Exercise-Based Fitness Activities" },
      { code: "NSTP2", name: "National Service Training Program 2" },
      { code: "REL2", name: "The New Testament" },
      { code: "HUMSS2", name: "Trends, Networks, Critical Thinking in the 21st Century" },
      { code: "ENG 2", name: "Basic English 2" },
    ],
    "2nd Year": [
      { code: "FIL", name: "Masining na Pagpapahayag" },
      { code: "PROFED3", name: "Building & Enhancing New Literacies Across the Curriculum" },
      { code: "PROFED4", name: "Facilitating Learner-Centered Teaching" },
      { code: "PROFED5", name: "Assessment in Learning 1" },
      { code: "EL4", name: "Principles & Theories of Language Acquisition & Learning" },
      { code: "EL5", name: "Teaching & Assessment of the Macroskills" },
      { code: "EL6", name: "Teaching & Assessment of Grammar" },
      { code: "EL7", name: "Technical Writing" },
      { code: "EL8", name: "Speech & Theater Arts" },
      { code: "PATHFIT3", name: "Physical Activities Toward Health and Fitness 3: Sports" },
      { code: "REL 3", name: "Biblical Interpretation in the Phil. Context" },
      { code: "GE EL1", name: "Gender and Society" },
      { code: "PROFED6", name: "Foundation of Special & Inclusive Education" },
      { code: "PROFED8", name: "Assessment in Learning 2" },
      { code: "EL9", name: "Language Programs & Policies in Multilingual Societies" },
      { code: "EL10", name: "Children & Adolescent Literature" },
      { code: "EL11", name: "Mythology & Folklore" },
      { code: "EL12", name: "Language Education Research" },
      { code: "PATHFIT4", name: "Physical Activities Toward Health and Fitness 4: Dance" },
    ],
    "3rd Year": [
      { code: "GE9", name: "The Life & Works of Rizal" },
      { code: "PROFED7", name: "The Teacher & the School Curriculum" },
      { code: "EL13", name: "Contemporary, Popular & Emergent Literature" },
      { code: "EL14", name: "Survey of Afro-Asian Literature" },
      { code: "EL15", name: "Survey of Philippine Literature in English" },
      { code: "EL16", name: "Survey of English & American Literature" },
      { code: "EL17", name: "Technology for Teaching & Learning 2 (Technology in Language Education)" },
      { code: "PROFED9", name: "The Teaching Profession" },
      { code: "PROFED10", name: "The Teacher and the Community, School Culture & Organizational Leadership" },
      { code: "EL18", name: "Language Learning Materials Development" },
      { code: "EL19", name: "Literary Criticism" },
      { code: "EL20", name: "Campus Journalism" },
      { code: "ELC1", name: "Remedial Instruction in English" },
      { code: "GE EL3", name: "Great Books" },
      { code: "EI 20", name: "Teaching & Assessment of Literature Studies" },
      { code: "ELC2", name: "Translation" },
    ],
    "4th Year": [
      { code: "FS1", name: "Observation of Teaching-Learning in Actual School Environment" },
      { code: "FS2", name: "Participation & Teaching Assistantship" },
      { code: "RES", name: "Research in Education II" },
      { code: "PRCTCHNG", name: "Teaching Internship" },
      { code: "ENRICHMENT", name: "Professional Enrichment Course" },
    ],
  },

  "BS Information Technology": {
    "1st Year": [
      { code: "CC101", name: "Introduction to Computing" },
      { code: "CC102", name: "Computer Programming 1" },
      { code: "HSS101", name: "Hardware Systems and Servicing" },
      { code: "GE1", name: "Understanding the Self" },
      { code: "GE4", name: "Mathematics in the Modern World" },
      { code: "GE5", name: "Purposive Communication" },
      { code: "Rel1+", name: "The Old Testament" },
      { code: "PATHFit1", name: "Physical Activities Toward Health and Fitness 1: Movement Competency Training" },
      { code: "NSTP1", name: "National Service Training Program" },
      { code: "CC103", name: "Computer Programming 2" },
      { code: "HCI101", name: "Introduction to Human Computer Interaction" },
      { code: "MS101", name: "Discrete Mathematics" },
      { code: "GE2", name: "Readings in Philippine History" },
      { code: "GE9", name: "Life and Works of Rizal" },
      { code: "GE(Elec1)", name: "Living in the IT Era" },
      { code: "Rel2+", name: "The New Testament" },
      { code: "PATHFit2", name: "Physical Activities Toward Health and Fitness 2: Exercise-Based Fitness Activities" },
      { code: "NSTP2", name: "National Service Training Program" },
    ],
    "2nd Year": [
      { code: "CC104", name: "Data Structures and Algorithms" },
      { code: "PF101", name: "(ProfElec) Object Oriented Programming" },
      { code: "PT101", name: "(ProfElec) Platform Technologies" },
      { code: "GE3", name: "The Contemporary World" },
      { code: "GE6", name: "Art Appreciation" },
      { code: "GE(Elec2)", name: "Gender and Society" },
      { code: "Rel3+", name: "Biblical Interpretation/Values" },
      { code: "PATHFit3", name: "Physical Activities Toward Health and Fitness 3: Sports" },
      { code: "CC105", name: "Information Management 1" },
      { code: "MS102", name: "Quantitative Methods (incl. Modeling & Simulation)" },
      { code: "NET101", name: "Networking 1" },
      { code: "IPT101", name: "Integrative Programming and Technologies 1" },
      { code: "GE7", name: "Science, Technology, and Society" },
      { code: "GE8", name: "Ethics" },
      { code: "GE(Elec3)", name: "Philippine Popular Culture" },
      { code: "PATHFit4", name: "Physical Activities Toward Health and Fitness 4: Dance" },
    ],
    "3rd Year": [
      { code: "IM101", name: "Fundamentals of Database Systems" },
      { code: "NET102", name: "Networking 2" },
      { code: "SIA101", name: "Systems Integration and Architecture 1" },
      { code: "IPT102", name: "(ProfElec) Integrative Programming and Technologies 2" },
      { code: "SAD101", name: "Systems Analysis, Design, and Development" },
      { code: "WS101", name: "(ProfElec) Web Systems & Technologies" },
      { code: "CC106", name: "Applications Development & Emerging Technologies" },
      { code: "IAS101", name: "Information Assurance and Security 1" },
      { code: "SP101", name: "Social and Professional Issues" },
      { code: "GIS101", name: "Geographical Information System and Tour" },
      { code: "HCI102", name: "(ProfElec) Human Computer Interaction 2" },
      { code: "SA101", name: "Systems Administration and Maintenance" },
      { code: "CAP101", name: "Capstone Project 1" },
    ],
    "4th Year": [
      { code: "IAS102", name: "Information Assurance and Security 2" },
      { code: "SIA102", name: "(ProfElec) Systems Integration and Architecture 2" },
      { code: "CAP102", name: "Capstone Project 2" },
      { code: "PRAC101", name: "Practicum (486 hrs.)" },
    ],
  },

  "Bachelor of Elementary Education": {
    "1st Year": [
      { code: "GE1", name: "Understanding the Self" },
      { code: "GE2", name: "Readings in Philippine History" },
      { code: "GE3", name: "The Contemporary World" },
      { code: "GE4", name: "Mathematics in the Modern World" },
      { code: "ELEM1", name: "Content and Pedagogy for the Mother Tongue" },
      { code: "ELEM2", name: "Pagtuturo ng Filipino sa Elementarya I – Estruktura at Gamit ng Wikang Filipino" },
      { code: "PROFED1", name: "The Child & Adolescent Learners & Learning Principles" },
      { code: "PATHFIT1", name: "Physical Activities Toward Health and Fitness 1: Movement Competency Training" },
      { code: "NSTP1", name: "National Service Training Program 1" },
      { code: "REL 1", name: "The Old Testament" },
      { code: "HUMSS1", name: "Philippine Politics & Governance" },
      { code: "ENG 1", name: "Basic English 1" },
      { code: "GE5", name: "Purposive Communication" },
      { code: "GE6", name: "Art Appreciation" },
      { code: "GE7", name: "Science, Technology & Society" },
      { code: "GE8", name: "Ethics" },
      { code: "ELEM3", name: "Teaching Math in the Primary Grades" },
      { code: "ELEM4", name: "Teaching Science in the Elementary Grades (Biology & Chemistry)" },
      { code: "PROFED2", name: "Technology for Teaching & Learning 1" },
      { code: "PATHFIT2", name: "Physical Activities Toward Health and Fitness 2: Exercise-Based Fitness Activities" },
      { code: "NSTP2", name: "National Service Training Program 2" },
      { code: "REL2", name: "The New Testament" },
      { code: "HUMSS2", name: "Trends, Networks, Critical Thinking in the 21st Century" },
      { code: "ENG 2", name: "Basic English 2" },
    ],
    "2nd Year": [
      { code: "FIL1", name: "Masining na Pagpapahayag" },
      { code: "PROFED3", name: "Building & Enhancing New Literacies Across the Curriculum" },
      { code: "PROFED4", name: "Facilitating Learner-Centered Teaching" },
      { code: "PROFED5", name: "Assessment in Learning 1" },
      { code: "ELEM5", name: "Teaching Social Studies in the Elem. Grades (Culture & Geography)" },
      { code: "ELEM6", name: "Good Manners & Right Conduct (Edukasyon sa Pagpapakatao)" },
      { code: "ELEM7", name: "Teaching PE and Health in the Elementary Grades" },
      { code: "PATHFIT3", name: "Physical Activities Toward Health and Fitness 3: Sports" },
      { code: "GE EL1", name: "Gender and Society" },
      { code: "PROFED6", name: "Foundation of Special & Inclusive Education" },
      { code: "PROFED8", name: "Assessment in Learning 2" },
      { code: "ELEM8", name: "Teaching Science in the Elem. Grades (Physics, Earth & Space Science)" },
      { code: "ELEM9", name: "Teaching Math in the Intermediate Grades" },
      { code: "ELEM10", name: "Teaching Social Studies in Elem. Grades (Phil. History & Government)" },
      { code: "ELEM11", name: "Teaching English in the Elementary Grades (Language Arts)" },
      { code: "ELEM12", name: "Edukasyong Pantahanan at Pangkabuhayan" },
      { code: "PATHFIT4", name: "Physical Activities Toward Health and Fitness 4: Dance" },
    ],
    "3rd Year": [
      { code: "GE9", name: "The Life & Works of Rizal" },
      { code: "PROFED7", name: "The Teacher & the School Curriculum" },
      { code: "ELEM13", name: "Teaching Music in the Elementary Grades" },
      { code: "ELEM14", name: "Teaching English in the Elementary Grades Through Literature" },
      { code: "ELEM15", name: "Teaching Arts in the Elementary Grades" },
      { code: "ELEM16", name: "Teaching Multi-Grade Classes" },
      { code: "ELEM17", name: "Technology for Teaching & Learning in the Elementary Grades" },
      { code: "PROFED9", name: "The Teaching Profession" },
      { code: "PROFED10", name: "The Teacher and the Community, School Culture & Organizational Leadership" },
      { code: "ELEM18", name: "Pagtuturo ng Filipino sa Elementarya II – Panitikan ng Pilipinas" },
      { code: "ELEM19", name: "Research in Education" },
      { code: "ELEM20", name: "Edukasyong Pantahanan at Pangkabuhayan with Entrepreneurship" },
      { code: "GE EL3", name: "Great Books" },
    ],
    "4th Year": [
      { code: "FS1", name: "Observation of Teaching-Learning in Actual School Environment" },
      { code: "FS2", name: "Participation & Teaching Assistantship" },
      { code: "RES", name: "Research in Education II" },
      { code: "PRCTCHNG", name: "Teaching Internship" },
      { code: "ENRICHMENT", name: "Professional Enrichment Course" },
    ],
  },
};

/* Programs (BSBA, BSEd) that need a major to resolve a curriculum
   are looked up with "<program>|<major>" first; everything else
   falls back to the plain program key. */
function getCurriculumSubjects(program: string, major: string, yearLevel: string): CurriculumSubject[] {
  if (!program || !yearLevel) return [];

  const compositeKey = major ? `${program}|${major}` : "";
  const table = (compositeKey && CURRICULUM_DATA[compositeKey]) || CURRICULUM_DATA[program];

  if (!table) return [];
  return table[yearLevel] || [];
}

(window as any).CURRICULUM_DATA = CURRICULUM_DATA;
(window as any).getCurriculumSubjects = getCurriculumSubjects;
